<a href="https://colab.research.google.com/github/Mercy-Kamau/Machine-Learning/blob/main/ML_Task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LassoCV
import matplotlib.pyplot as plt
import seaborn as sns
#%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel

# Prepare the Dataset

In [ ]:
data=pd.read_csv('/content/modified_data.csv')

In [69]:
data

MSSubClass MSZoning  LotFrontage  LotArea  Street  LotShape LandContour  \
0             60       RL         65.0     8450       1         3         Lvl   
1             20       RL         80.0     9600       1         3         Lvl   
2             60       RL         68.0    11250       1         0         Lvl   
3             70       RL         60.0     9550       1         0         Lvl   
4             60       RL         84.0    14260       1         0         Lvl   
...          ...      ...          ...      ...     ...       ...         ...   
1455          60       RL         62.0     7917       1         3         Lvl   
1456          20       RL         85.0    13175       1         3         Lvl   
1457          70       RL         66.0     9042       1         3         Lvl   
1458          20       RL         68.0     9717       1         3         Lvl   
1459          20       RL         75.0     9937       1         3         Lvl   

      Utilities  LotConfig  LandSlope  ... EnclosedPorch  3SsnPorch  \
0             0          4          0  ...             0          0   
1             0          2          0  ...             0          0   
2             0          4          0  ...             0          0   
3             0          0          0  ...           272          0   
4             0          2          0  ...             0          0   
...         ...        ...        ...  ...           ...        ...   
1455          0          4          0  ...             0          0   
1456          0          4          0  ...             0          0   
1457          0          4          0  ...             0          0   
1458          0          4          0  ...           112          0   
1459          0          4          0  ...             0          0   

      ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  SaleCondition  \
0               0         0        0       2    2008         8              4   
1               0         0        0       5    2007         8              4   
2               0         0        0       9    2008         8              4   
3               0         0        0       2    2006         8              0   
4               0         0        0      12    2008         8              4   
...           ...       ...      ...     ...     ...       ...            ...   
1455            0         0        0       8    2007         8              4   
1456            0         0        0       2    2010         8              4   
1457            0         0     2500       5    2010         8              4   
1458            0         0        0       4    2010         8              4   
1459            0         0        0       6    2008         8              4   

      SalePrice  
0        208500  
1        181500  
2        223500  
3        140000  
4        250000  
...         ...  
1455     175000  
1456     210000  
1457     266500  
1458     142125  
1459     147500  

[1460 rows x 76 columns]

In [ ]:
data.shape

In [ ]:
data.drop('Id',inplace = True, axis =1)

In [ ]:
data

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0             60       RL         65.0     8450   Pave      Reg         Lvl   
1             20       RL         80.0     9600   Pave      Reg         Lvl   
2             60       RL         68.0    11250   Pave      IR1         Lvl   
3             70       RL         60.0     9550   Pave      IR1         Lvl   
4             60       RL         84.0    14260   Pave      IR1         Lvl   
...          ...      ...          ...      ...    ...      ...         ...   
1455          60       RL         62.0     7917   Pave      Reg         Lvl   
1456          20       RL         85.0    13175   Pave      Reg         Lvl   
1457          70       RL         66.0     9042   Pave      Reg         Lvl   
1458          20       RL         68.0     9717   Pave      Reg         Lvl   
1459          20       RL         75.0     9937   Pave      Reg         Lvl   

     Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0       AllPub    Inside       Gtl  ...             0         0           0   
1       AllPub       FR2       Gtl  ...             0         0           0   
2       AllPub    Inside       Gtl  ...             0         0           0   
3       AllPub    Corner       Gtl  ...           272         0           0   
4       AllPub       FR2       Gtl  ...             0         0           0   
...        ...       ...       ...  ...           ...       ...         ...   
1455    AllPub    Inside       Gtl  ...             0         0           0   
1456    AllPub    Inside       Gtl  ...             0         0           0   
1457    AllPub    Inside       Gtl  ...             0         0           0   
1458    AllPub    Inside       Gtl  ...           112         0           0   
1459    AllPub    Inside       Gtl  ...             0         0           0   

     PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0           0       0       2    2008        WD         Normal    208500  
1           0       0       5    2007        WD         Normal    181500  
2           0       0       9    2008        WD         Normal    223500  
3           0       0       2    2006        WD        Abnorml    140000  
4           0       0      12    2008        WD         Normal    250000  
...       ...     ...     ...     ...       ...            ...       ...  
1455        0       0       8    2007        WD         Normal    175000  
1456        0       0       2    2010        WD         Normal    210000  
1457        0    2500       5    2010        WD         Normal    266500  
1458        0       0       4    2010        WD         Normal    142125  
1459        0       0       6    2008        WD         Normal    147500  

[1460 rows x 76 columns]

In [ ]:
old_features=list(data.columns)
len(old_features)

76

# Fill in Missing Values

In [ ]:
missing_values= list(data.columns[data.isna().any()])
len(missing_values)

15

In [ ]:
bfill,mean_fill=[],[]


In [ ]:
for feature in missing_values:
  print(feature,' ',data[feature].isna().sum()/len(data)*100,' ',data[feature].dtype)
  if data[feature].dtype=='float64':
    mean_fill.append(feature)
  else:
    bfill.append(feature)

LotFrontage   17.73972602739726   float64
MasVnrType   0.547945205479452   object
MasVnrArea   0.547945205479452   float64
BsmtQual   2.5342465753424657   object
BsmtCond   2.5342465753424657   object
BsmtExposure   2.6027397260273974   object
BsmtFinType1   2.5342465753424657   object
BsmtFinType2   2.6027397260273974   object
Electrical   0.0684931506849315   object
FireplaceQu   47.26027397260274   object
GarageType   5.5479452054794525   object
GarageYrBlt   5.5479452054794525   float64
GarageFinish   5.5479452054794525   object
GarageQual   5.5479452054794525   object
GarageCond   5.5479452054794525   object


In [ ]:
mean_fill

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [ ]:
for feature in mean_fill:
  data[feature].fillna(data[feature].mean(),inplace=True)

In [ ]:
for feature in bfill:
  data[feature].fillna(method='bfill',inplace=True)

In [ ]:
data.columns[data.isna().any()]

Index(['FireplaceQu'], dtype='object')

In [ ]:
data['FireplaceQu'].isna().sum()

2

In [ ]:

data['FireplaceQu'].fillna(method='ffill',inplace=True)

In [ ]:
data.head(100)


MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0           60       RL    65.000000     8450   Pave      Reg         Lvl   
1           20       RL    80.000000     9600   Pave      Reg         Lvl   
2           60       RL    68.000000    11250   Pave      IR1         Lvl   
3           70       RL    60.000000     9550   Pave      IR1         Lvl   
4           60       RL    84.000000    14260   Pave      IR1         Lvl   
..         ...      ...          ...      ...    ...      ...         ...   
95          60       RL    70.049958     9765   Pave      IR2         Lvl   
96          20       RL    78.000000    10264   Pave      IR1         Lvl   
97          20       RL    73.000000    10921   Pave      Reg         HLS   
98          30       RL    85.000000    10625   Pave      Reg         Lvl   
99          20       RL    77.000000     9320   Pave      IR1         Lvl   

   Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0     AllPub    Inside       Gtl  ...             0         0           0   
1     AllPub       FR2       Gtl  ...             0         0           0   
2     AllPub    Inside       Gtl  ...             0         0           0   
3     AllPub    Corner       Gtl  ...           272         0           0   
4     AllPub       FR2       Gtl  ...             0         0           0   
..       ...       ...       ...  ...           ...       ...         ...   
95    AllPub    Corner       Gtl  ...             0         0           0   
96    AllPub    Inside       Gtl  ...             0         0           0   
97    AllPub    Inside       Gtl  ...             0         0           0   
98    AllPub    Corner       Gtl  ...            77         0           0   
99    AllPub    Inside       Gtl  ...             0         0           0   

   PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0         0       0       2    2008        WD         Normal    208500  
1         0       0       5    2007        WD         Normal    181500  
2         0       0       9    2008        WD         Normal    223500  
3         0       0       2    2006        WD        Abnorml    140000  
4         0       0      12    2008        WD         Normal    250000  
..      ...     ...     ...     ...       ...            ...       ...  
95        0     480       4    2009        WD         Normal    185000  
96        0       0       8    2006        WD         Normal    214000  
97        0       0       5    2007        WD         Normal     94750  
98        0     400       5    2010       COD        Abnorml     83000  
99        0     400       1    2010        WD         Normal    128950  

[100 rows x 76 columns]

In [ ]:
data['FireplaceQu'].head(100)


0     TA
1     TA
2     TA
3     Gd
4     TA
      ..
95    TA
96    TA
97    TA
98    TA
99    TA
Name: FireplaceQu, Length: 100, dtype: object

# Encode the dataset

In [70]:
categorical_features=list(data.select_dtypes(include=['object']).columns)
categorical_features

['MSZoning', 'LandContour', 'Neighborhood']

In [71]:
data[categorical_features].head(5)

MSZoning LandContour Neighborhood
0       RL         Lvl      CollgCr
1       RL         Lvl      Veenker
2       RL         Lvl      CollgCr
3       RL         Lvl      Crawfor
4       RL         Lvl      NoRidge

In [ ]:
numerical=list(set(old_features)-set(categorical_features))
numerical

In [96]:
data[numerical].head(5)

GarageArea  OpenPorchSF  EnclosedPorch  PoolArea  3SsnPorch  YrSold  \
0         548           61              0         0          0    2008   
1         460            0              0         0          0    2007   
2         608           42              0         0          0    2008   
3         642           35            272         0          0    2006   
4         836           84              0         0          0    2008   

   TotRmsAbvGrd  1stFlrSF  2ndFlrSF  GarageCars  ...  BsmtFinSF1  TotalBsmtSF  \
0             8       856       854           2  ...         706          856   
1             6      1262         0           2  ...         978         1262   
2             6       920       866           2  ...         486          920   
3             7       961       756           3  ...         216          756   
4             9      1145      1053           3  ...         655         1145   

   ScreenPorch  LowQualFinSF  KitchenAbvGr  OverallCond  Fireplaces  \
0            0             0             1            5           0   
1            0             0             1            8           1   
2            0             0             1            5           1   
3            0             0             1            5           1   
4            0             0             1            5           1   

   BsmtHalfBath  MoSold  GarageYrBlt  
0             0       2       2003.0  
1             1       5       1976.0  
2             0       9       2001.0  
3             0       2       1998.0  
4             0      12       2000.0  

[5 rows x 37 columns]

In [ ]:
nominal=['MSZoning','LandContour','Neighborhood']
ordinal=list(set(categorical_features)-set(nominal))

In [ ]:
data[nominal].head(5)

In [ ]:
ordinal

In [ ]:
data[ordinal].head(5)

In [ ]:
target=['SalePrice']

In [ ]:
df_nominal=pd.get_dummies(data[nominal])

In [ ]:
for feature in ordinal:
  data[feature]=data[feature].astype('category').cat.codes

df_ordinal=data[ordinal]

In [73]:
new_data=pd.concat([df_nominal,df_ordinal,data[numerical]],axis=1)

In [ ]:
new_data.shape

# Standardize the dataset

In [ ]:
new_data.drop('SalePrice',axis=1,inplace=True)

In [ ]:
X=new_data.to_numpy()

In [ ]:
X[0]

array([0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 3.000e+00, 4.000e+00,
       4.000e+00, 2.000e+00, 1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
       2.000e+00, 1.000e+00, 1.000e+00, 8.000e+00, 3.000e+00, 4.000e+00,
       4.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 6.000e+00,
       2.000e+00, 1.300e+01, 5.000e+00, 1.200e+01, 3.000e+00, 1.000e+00,
       4.000e+00, 5.000e+00, 1.000e+00, 4.000e+00, 2.000e+00, 4.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 1.000e+00, 1.000e+00,
       1.500e+02, 0.000e+00, 7.060e+02, 6.500e+01, 0.000e+00, 2.003e+03,
       8.450e+03, 3.000e+00, 0.000e+00, 8.560e+02, 

In [ ]:
X=StandardScaler().fit_transform(X)

In [ ]:
X[0]

array([-0.08304548, -0.21585871, -0.10526316,  0.51813339, -0.41895507,
       -0.21235968, -0.18831089, -0.15899968,  0.33712564, -0.10854037,
       -0.03703704, -0.10526316, -0.20339487, -0.1398323 ,  2.95522137,
       -0.19025216, -0.27116307, -0.23917551, -0.16124951, -0.10854037,
       -0.1863522 , -0.42683279, -0.07875671, -0.22941573, -0.16998114,
       -0.23595776, -0.28963792, -0.13199092, -0.23106504, -0.20521398,
       -0.25018188, -0.13199092, -0.16347148, -0.08712888,  0.75073056,
        0.22403433,  0.36420746,  0.28974476, -1.23804229, -0.88465767,
        0.06423821, -0.41169079, -0.29055229, -0.12304604,  0.26381257,
        0.31386709,  0.64046232,  0.2085023 ,  0.303692  , -0.22571613,
       -0.02618016, -0.49151573, -0.23012211,  0.25597761, -0.03628912,
        0.75162623,  1.02668924,  0.74309239,  0.28780036, -0.12579688,
        1.11993319,  0.30941909, -0.71775144,  0.60466978, -0.40936914,
        0.18797343, -0.40779461, -0.77797579,  0.83559903, -0.03

In [ ]:
y=data[target]

In [ ]:
y=y.to_numpy()

In [ ]:
y.shape

(1460, 1)

In [ ]:
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [ ]:
y=StandardScaler().fit_transform(y)

In [ ]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

In [ ]:
X.shape

(1460, 106)

# Perfom feature extraction using PCA

In [75]:
pca=PCA(n_components=2)

In [76]:
p_components=pca.fit_transform(X)

In [77]:
p_components

array([[ 2.44331019, -1.27882337],
       [ 0.31646008,  2.63817521],
       [ 2.85722117, -0.81106049],
       ...,
       [ 1.26182513, -0.86150349],
       [-2.8509665 ,  3.29482929],
       [-0.7773861 ,  2.79004847]])

In [78]:
pca.explained_variance_ratio_

array([0.10560233, 0.04472091])

# Perform feature selection using L1

### Separating the data into training and tests set

In [81]:
X_train, X_test, y_train, y_test = train_test_split(
    new_data.drop(labels=['SalePrice'], axis=1),
    new_data['SalePrice'],
    test_size=0.3,
    random_state=0)
X_train.shape, X_test.shape

((1022, 106), (438, 106))

### Scaling the data, as linear models benefits from feature scaling

In [82]:
scaler = StandardScaler()
scaler.fit(X_train.fillna(0))

StandardScaler()

### Selecting features using Lasso regularisation using SelectFromModel

In [85]:
sel = SelectFromModel(LogisticRegression(C=1, penalty='l1', solver='liblinear'))
sel.fit(scaler.transform(X_train.fillna(0)), y_train)

SelectFromModel(estimator=LogisticRegression(C=1, penalty='l1',
                                             solver='liblinear'))

In [89]:
new_data.head()

MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0                 0            0            0            1            0   
1                 0            0            0            1            0   
2                 0            0            0            1            0   
3                 0            0            0            1            0   
4                 0            0            0            1            0   

   LandContour_Bnk  LandContour_HLS  LandContour_Low  LandContour_Lvl  \
0                0                0                0                1   
1                0                0                0                1   
2                0                0                0                1   
3                0                0                0                1   
4                0                0                0                1   

   Neighborhood_Blmngtn  ...  BsmtFinSF1  TotalBsmtSF  ScreenPorch  \
0                     0  ...         706          856            0   
1                     0  ...         978         1262            0   
2                     0  ...         486          920            0   
3                     0  ...         216          756            0   
4                     0  ...         655         1145            0   

   LowQualFinSF  KitchenAbvGr  OverallCond  Fireplaces  BsmtHalfBath  MoSold  \
0             0             1            5           0             0       2   
1             0             1            8           1             1       5   
2             0             1            5           1             0       9   
3             0             1            5           1             0       2   
4             0             1            5           1             0      12   

   GarageYrBlt  
0       2003.0  
1       1976.0  
2       2001.0  
3       1998.0  
4       2000.0  

[5 rows x 107 columns]

In [90]:
new_data.shape

(1460, 107)

In [93]:
#visualize features kept
sel.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [95]:
#Make a list with selected features

selected_features= X_train.columns[(sel.get_support())]
selected_features

Index(['MSZoning_C (all)', 'MSZoning_FV', 'MSZoning_RH', 'MSZoning_RL',
       'MSZoning_RM', 'LandContour_Bnk', 'LandContour_HLS', 'LandContour_Low',
       'LandContour_Lvl', 'Neighborhood_Blmngtn',
       ...
       'BsmtFinSF1', 'TotalBsmtSF', 'ScreenPorch', 'LowQualFinSF',
       'KitchenAbvGr', 'OverallCond', 'Fireplaces', 'BsmtHalfBath', 'MoSold',
       'GarageYrBlt'],
      dtype='object', length=106)

# Train a regression model using PCA with 2 compnents

In [91]:
reg=LassoCV()

In [92]:
reg.fit(p_components,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1571: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV()

In [ ]:
reg.coef_

In [ ]:
y = W_1*x_1 + W_2*x_2 

In [ ]:
y=mx+c

In [ ]:
y=wx+b