<a href="https://colab.research.google.com/github/Mercy-Kamau/Machine-Learning/blob/main/ML_Task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LassoCV
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn import linear_model,metrics
from sklearn.linear_model import Lasso, LogisticRegression
from sklearn.feature_selection import SelectFromModel

# Prepare the Dataset

In [44]:
first_data=pd.read_csv('/content/modified_data.csv')

In [45]:
first_data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0   1          60       RL         65.0     8450   Pave      Reg         Lvl   
1   2          20       RL         80.0     9600   Pave      Reg         Lvl   
2   3          60       RL         68.0    11250   Pave      IR1         Lvl   
3   4          70       RL         60.0     9550   Pave      IR1         Lvl   
4   5          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch PoolArea  \
0    AllPub    Inside  ...             0         0           0        0   
1    AllPub       FR2  ...             0         0           0        0   
2    AllPub    Inside  ...             0         0           0        0   
3    AllPub    Corner  ...           272         0           0        0   
4    AllPub       FR2  ...             0         0           0        0   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0       0      2    2008        WD         Normal     208500  
1       0      5    2007        WD         Normal     181500  
2       0      9    2008        WD         Normal     223500  
3       0      2    2006        WD        Abnorml     140000  
4       0     12    2008        WD         Normal     250000  

[5 rows x 77 columns]

In [46]:
first_data.shape

(1460, 77)

In [47]:
first_data.drop('Id',inplace = True, axis =1)


In [48]:
first_data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL         65.0     8450   Pave      Reg         Lvl   
1          20       RL         80.0     9600   Pave      Reg         Lvl   
2          60       RL         68.0    11250   Pave      IR1         Lvl   
3          70       RL         60.0     9550   Pave      IR1         Lvl   
4          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   
1    AllPub       FR2       Gtl  ...             0         0           0   
2    AllPub    Inside       Gtl  ...             0         0           0   
3    AllPub    Corner       Gtl  ...           272         0           0   
4    AllPub       FR2       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  
1        0       0       5    2007        WD         Normal    181500  
2        0       0       9    2008        WD         Normal    223500  
3        0       0       2    2006        WD        Abnorml    140000  
4        0       0      12    2008        WD         Normal    250000  

[5 rows x 76 columns]

In [49]:
old_features=list(first_data.columns)
len(old_features)

76

# Fill in Missing Values

In [50]:
missing_values= list(first_data.columns[first_data.isna().any()])
len(missing_values)

15

In [51]:
bfill,mean_fill=[],[]


In [52]:
for feature in missing_values:
  print(feature,' ',first_data[feature].isna().sum()/len(first_data)*100,' ',first_data[feature].dtype)
  if first_data[feature].dtype=='float64':
    mean_fill.append(feature)
  else:
    bfill.append(feature)

LotFrontage   17.73972602739726   float64
MasVnrType   0.547945205479452   object
MasVnrArea   0.547945205479452   float64
BsmtQual   2.5342465753424657   object
BsmtCond   2.5342465753424657   object
BsmtExposure   2.6027397260273974   object
BsmtFinType1   2.5342465753424657   object
BsmtFinType2   2.6027397260273974   object
Electrical   0.0684931506849315   object
FireplaceQu   47.26027397260274   object
GarageType   5.5479452054794525   object
GarageYrBlt   5.5479452054794525   float64
GarageFinish   5.5479452054794525   object
GarageQual   5.5479452054794525   object
GarageCond   5.5479452054794525   object


In [53]:
mean_fill

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [54]:
for feature in mean_fill:
  first_data[feature].fillna(first_data[feature].mean(),inplace=True)

In [55]:
for feature in bfill:
  first_data[feature].fillna(method='bfill',inplace=True)

In [56]:
first_data.columns[first_data.isna().any()]

Index(['FireplaceQu'], dtype='object')

In [57]:
first_data['FireplaceQu'].isna().sum()

2

In [58]:

first_data['FireplaceQu'].fillna(method='ffill',inplace=True)

In [59]:
first_data.head(10)


MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL    65.000000     8450   Pave      Reg         Lvl   
1          20       RL    80.000000     9600   Pave      Reg         Lvl   
2          60       RL    68.000000    11250   Pave      IR1         Lvl   
3          70       RL    60.000000     9550   Pave      IR1         Lvl   
4          60       RL    84.000000    14260   Pave      IR1         Lvl   
5          50       RL    85.000000    14115   Pave      IR1         Lvl   
6          20       RL    75.000000    10084   Pave      Reg         Lvl   
7          60       RL    70.049958    10382   Pave      IR1         Lvl   
8          50       RM    51.000000     6120   Pave      Reg         Lvl   
9         190       RL    50.000000     7420   Pave      Reg         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   
1    AllPub       FR2       Gtl  ...             0         0           0   
2    AllPub    Inside       Gtl  ...             0         0           0   
3    AllPub    Corner       Gtl  ...           272         0           0   
4    AllPub       FR2       Gtl  ...             0         0           0   
5    AllPub    Inside       Gtl  ...             0       320           0   
6    AllPub    Inside       Gtl  ...             0         0           0   
7    AllPub    Corner       Gtl  ...           228         0           0   
8    AllPub    Inside       Gtl  ...           205         0           0   
9    AllPub    Corner       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  
1        0       0       5    2007        WD         Normal    181500  
2        0       0       9    2008        WD         Normal    223500  
3        0       0       2    2006        WD        Abnorml    140000  
4        0       0      12    2008        WD         Normal    250000  
5        0     700      10    2009        WD         Normal    143000  
6        0       0       8    2007        WD         Normal    307000  
7        0     350      11    2009        WD         Normal    200000  
8        0       0       4    2008        WD        Abnorml    129900  
9        0       0       1    2008        WD         Normal    118000  

[10 rows x 76 columns]

In [60]:
first_data['FireplaceQu'].head(10)


0    TA
1    TA
2    TA
3    Gd
4    TA
5    Gd
6    Gd
7    TA
8    TA
9    TA
Name: FireplaceQu, dtype: object

# Encode the dataset

In [61]:
categorical_features=list(first_data.select_dtypes(include=['object']).columns)
categorical_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [62]:
first_data.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL         65.0     8450   Pave      Reg         Lvl   
1          20       RL         80.0     9600   Pave      Reg         Lvl   
2          60       RL         68.0    11250   Pave      IR1         Lvl   
3          70       RL         60.0     9550   Pave      IR1         Lvl   
4          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   
1    AllPub       FR2       Gtl  ...             0         0           0   
2    AllPub    Inside       Gtl  ...             0         0           0   
3    AllPub    Corner       Gtl  ...           272         0           0   
4    AllPub       FR2       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  
1        0       0       5    2007        WD         Normal    181500  
2        0       0       9    2008        WD         Normal    223500  
3        0       0       2    2006        WD        Abnorml    140000  
4        0       0      12    2008        WD         Normal    250000  

[5 rows x 76 columns]

In [63]:
cd_data=first_data[categorical_features].head(5)
cd_data

MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
0       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1       RL   Pave      Reg         Lvl    AllPub       FR2       Gtl   
2       RL   Pave      IR1         Lvl    AllPub    Inside       Gtl   
3       RL   Pave      IR1         Lvl    AllPub    Corner       Gtl   
4       RL   Pave      IR1         Lvl    AllPub       FR2       Gtl   

  Neighborhood Condition1 Condition2  ... KitchenQual Functional FireplaceQu  \
0      CollgCr       Norm       Norm  ...          Gd        Typ          TA   
1      Veenker      Feedr       Norm  ...          TA        Typ          TA   
2      CollgCr       Norm       Norm  ...          Gd        Typ          TA   
3      Crawfor       Norm       Norm  ...          Gd        Typ          Gd   
4      NoRidge       Norm       Norm  ...          Gd        Typ          TA   

  GarageType GarageFinish GarageQual GarageCond PavedDrive SaleType  \
0     Attchd          RFn         TA         TA          Y       WD   
1     Attchd          RFn         TA         TA          Y       WD   
2     Attchd          RFn         TA         TA          Y       WD   
3     Detchd          Unf         TA         TA          Y       WD   
4     Attchd          RFn         TA         TA          Y       WD   

  SaleCondition  
0        Normal  
1        Normal  
2        Normal  
3       Abnorml  
4        Normal  

[5 rows x 39 columns]

In [64]:
numerical=list(set(old_features)-set(categorical_features))
numerical

['2ndFlrSF',
 'BsmtFinSF2',
 'PoolArea',
 'HalfBath',
 'BsmtFinSF1',
 'MasVnrArea',
 'TotRmsAbvGrd',
 '3SsnPorch',
 'OpenPorchSF',
 'LowQualFinSF',
 '1stFlrSF',
 'MSSubClass',
 'GarageArea',
 'YrSold',
 'BsmtFullBath',
 'MiscVal',
 'LotFrontage',
 'BsmtUnfSF',
 'EnclosedPorch',
 'YearRemodAdd',
 'GrLivArea',
 'GarageYrBlt',
 'LotArea',
 'YearBuilt',
 'WoodDeckSF',
 'TotalBsmtSF',
 'MoSold',
 'KitchenAbvGr',
 'OverallCond',
 'GarageCars',
 'FullBath',
 'BedroomAbvGr',
 'SalePrice',
 'BsmtHalfBath',
 'OverallQual',
 'ScreenPorch',
 'Fireplaces']

In [65]:
first_data[numerical].head(5)


2ndFlrSF  BsmtFinSF2  PoolArea  HalfBath  BsmtFinSF1  MasVnrArea  \
0       854           0         0         1         706       196.0   
1         0           0         0         0         978         0.0   
2       866           0         0         1         486       162.0   
3       756           0         0         0         216         0.0   
4      1053           0         0         1         655       350.0   

   TotRmsAbvGrd  3SsnPorch  OpenPorchSF  LowQualFinSF  ...  KitchenAbvGr  \
0             8          0           61             0  ...             1   
1             6          0            0             0  ...             1   
2             6          0           42             0  ...             1   
3             7          0           35             0  ...             1   
4             9          0           84             0  ...             1   

   OverallCond  GarageCars  FullBath  BedroomAbvGr  SalePrice  BsmtHalfBath  \
0            5           2         2             3     208500             0   
1            8           2         2             3     181500             1   
2            5           2         2             3     223500             0   
3            5           3         1             3     140000             0   
4            5           3         2             4     250000             0   

   OverallQual  ScreenPorch  Fireplaces  
0            7            0           0  
1            6            0           1  
2            7            0           1  
3            7            0           1  
4            8            0           1  

[5 rows x 37 columns]

In [66]:
nominal=['MSZoning','LandContour','Neighborhood']
ordinal=list(set(categorical_features)-set(nominal))

In [67]:
first_data[nominal].head(5)

MSZoning LandContour Neighborhood
0       RL         Lvl      CollgCr
1       RL         Lvl      Veenker
2       RL         Lvl      CollgCr
3       RL         Lvl      Crawfor
4       RL         Lvl      NoRidge

In [68]:
ordinal

['BsmtCond',
 'RoofMatl',
 'Heating',
 'LotShape',
 'Foundation',
 'LotConfig',
 'LandSlope',
 'Exterior2nd',
 'ExterCond',
 'GarageFinish',
 'Electrical',
 'GarageCond',
 'MasVnrType',
 'Exterior1st',
 'Functional',
 'FireplaceQu',
 'SaleType',
 'Condition2',
 'GarageQual',
 'Condition1',
 'PavedDrive',
 'RoofStyle',
 'HeatingQC',
 'Street',
 'SaleCondition',
 'BsmtQual',
 'CentralAir',
 'Utilities',
 'KitchenQual',
 'BsmtFinType2',
 'HouseStyle',
 'BsmtExposure',
 'BldgType',
 'ExterQual',
 'GarageType',
 'BsmtFinType1']

In [69]:
first_data[ordinal].head(5)

BsmtCond RoofMatl Heating LotShape Foundation LotConfig LandSlope  \
0       TA  CompShg    GasA      Reg      PConc    Inside       Gtl   
1       TA  CompShg    GasA      Reg     CBlock       FR2       Gtl   
2       TA  CompShg    GasA      IR1      PConc    Inside       Gtl   
3       Gd  CompShg    GasA      IR1     BrkTil    Corner       Gtl   
4       TA  CompShg    GasA      IR1      PConc       FR2       Gtl   

  Exterior2nd ExterCond GarageFinish  ... CentralAir Utilities KitchenQual  \
0     VinylSd        TA          RFn  ...          Y    AllPub          Gd   
1     MetalSd        TA          RFn  ...          Y    AllPub          TA   
2     VinylSd        TA          RFn  ...          Y    AllPub          Gd   
3     Wd Shng        TA          Unf  ...          Y    AllPub          Gd   
4     VinylSd        TA          RFn  ...          Y    AllPub          Gd   

  BsmtFinType2 HouseStyle BsmtExposure BldgType ExterQual GarageType  \
0          Unf     2Story           No     1Fam        Gd     Attchd   
1          Unf     1Story           Gd     1Fam        TA     Attchd   
2          Unf     2Story           Mn     1Fam        Gd     Attchd   
3          Unf     2Story           No     1Fam        TA     Detchd   
4          Unf     2Story           Av     1Fam        Gd     Attchd   

  BsmtFinType1  
0          GLQ  
1          ALQ  
2          GLQ  
3          ALQ  
4          GLQ  

[5 rows x 36 columns]

In [70]:
target=['SalePrice']

In [71]:
df_nominal=pd.get_dummies(first_data[nominal])

In [72]:
for feature in ordinal:
  first_data[feature]=first_data[feature].astype('category').cat.codes

df_ordinal=first_data[ordinal]

In [73]:
new_data=pd.concat([df_nominal,df_ordinal,first_data[numerical]],axis=1)

In [74]:
new_data.shape

(1460, 107)

# Standardize the dataset

In [75]:
#dr=first_data.drop('SalePrice',axis=1,inplace=True)

In [76]:
X=new_data.to_numpy()

In [77]:
X[0]

array([0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 3.000e+00, 1.000e+00,
       1.000e+00, 3.000e+00, 2.000e+00, 4.000e+00, 0.000e+00, 1.300e+01,
       4.000e+00, 1.000e+00, 4.000e+00, 4.000e+00, 1.000e+00, 1.200e+01,
       6.000e+00, 4.000e+00, 8.000e+00, 2.000e+00, 4.000e+00, 2.000e+00,
       2.000e+00, 1.000e+00, 0.000e+00, 1.000e+00, 4.000e+00, 2.000e+00,
       1.000e+00, 0.000e+00, 2.000e+00, 5.000e+00, 5.000e+00, 3.000e+00,
       0.000e+00, 2.000e+00, 1.000e+00, 2.000e+00, 8.540e+02, 0.000e+00,
       0.000e+00, 1.000e+00, 7.060e+02, 1.960e+02, 8.000e+00, 0.000e+00,
       6.100e+01, 0.000e+00, 8.560e+02, 6.000e+01, 

In [78]:
X=StandardScaler().fit_transform(X)

In [79]:
X[0]

array([-0.08304548, -0.21585871, -0.10526316,  0.51813339, -0.41895507,
       -0.21235968, -0.18831089, -0.15899968,  0.33712564, -0.10854037,
       -0.03703704, -0.10526316, -0.20339487, -0.1398323 ,  2.95522137,
       -0.19025216, -0.27116307, -0.23917551, -0.16124951, -0.10854037,
       -0.1863522 , -0.42683279, -0.07875671, -0.22941573, -0.16998114,
       -0.23595776, -0.28963792, -0.13199092, -0.23106504, -0.20521398,
       -0.25018188, -0.13199092, -0.16347148, -0.08712888,  0.28780036,
       -0.12579688, -0.12304604,  0.75073056,  0.83559903,  0.60466978,
       -0.22571613,  0.75162623,  0.36420746, -0.23012211,  0.303692  ,
        0.18797343, -1.23804229,  0.74309239,  0.25597761,  1.11993319,
        0.31386709, -0.03174026,  0.22403433, -0.03628912,  0.28974476,
       -0.49151573, -0.88465767,  0.06423821,  0.2085023 , -0.29055229,
        0.26381257, -0.02618016, -0.40936914,  0.30941909,  1.02668924,
        0.64046232, -0.41169079, -0.77797579, -0.71775144, -0.40

In [80]:
y=first_data[target]

In [81]:
y=y.to_numpy()

In [82]:
y.shape

(1460, 1)

In [83]:
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [84]:
y=StandardScaler().fit_transform(y)

In [85]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

In [86]:
X.shape

(1460, 107)

# Perfom feature extraction using PCA

In [87]:
pca=PCA(n_components=2)

In [88]:
p_components=pca.fit_transform(X)

In [89]:
p_components

array([[ 2.41802006, -1.33318455],
       [ 0.31271424,  2.59681326],
       [ 2.86904698, -0.86088318],
       ...,
       [ 1.55378962, -0.74951328],
       [-2.87943293,  3.2648022 ],
       [-0.86718408,  2.74114864]])

In [90]:
pca.explained_variance_ratio_

array([0.11156105, 0.04432191])

# Perform feature selection using L1

### Separating the data into training and tests set

In [130]:
X_train, X_test, y_train, y_test = train_test_split(
    new_data.drop(labels=['SalePrice'], axis=1),
    new_data['SalePrice'],
    test_size=0.3,
    random_state=42)
X_train.shape, X_test.shape

((1022, 106), (438, 106))

### Scaling the data, as linear models benefits from feature scaling

In [131]:
scaler = StandardScaler()
scaler.fit(X_train.fillna(0))

StandardScaler()

### Selecting features using Lasso regularisation using SelectFromModel

In [132]:
sel = SelectFromModel(LogisticRegression(C=1, penalty='l1', solver='liblinear'))
sel.fit(scaler.transform(X_train.fillna(0)), y_train)

SelectFromModel(estimator=LogisticRegression(C=1, penalty='l1',
                                             solver='liblinear'))

In [133]:
new_data.head()

MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0                 0            0            0            1            0   
1                 0            0            0            1            0   
2                 0            0            0            1            0   
3                 0            0            0            1            0   
4                 0            0            0            1            0   

   LandContour_Bnk  LandContour_HLS  LandContour_Low  LandContour_Lvl  \
0                0                0                0                1   
1                0                0                0                1   
2                0                0                0                1   
3                0                0                0                1   
4                0                0                0                1   

   Neighborhood_Blmngtn  ...  KitchenAbvGr  OverallCond  GarageCars  FullBath  \
0                     0  ...             1            5           2         2   
1                     0  ...             1            8           2         2   
2                     0  ...             1            5           2         2   
3                     0  ...             1            5           3         1   
4                     0  ...             1            5           3         2   

   BedroomAbvGr  SalePrice  BsmtHalfBath  OverallQual  ScreenPorch  Fireplaces  
0             3     208500             0            7            0           0  
1             3     181500             1            6            0           1  
2             3     223500             0            7            0           1  
3             3     140000             0            7            0           1  
4             4     250000             0            8            0           1  

[5 rows x 107 columns]

In [120]:
new_data.shape

(1460, 107)

In [134]:
#visualize features kept
sel.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [128]:
selected_feat = X_train.columns[(sel.get_support())]
print('total features: {}'.format((X_train.shape[1])))
print('selected features: {}'.format(len(selected_feat)))


total features: 106
selected features: 106


In [135]:
X_train_selected = sel.transform(X_train.fillna(0))
X_test_selected = sel.transform(X_test.fillna(0))
  
X_train_selected.shape, X_test_selected.shape

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but SelectFromModel was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


((1022, 106), (438, 106))

In [136]:
result = {}
models = {'LinearRegression':linear_model.LinearRegression(),
          'Lasso':linear_model.Lasso(),
          'Ridge':linear_model.Ridge(),
          'ElasticNet':linear_model.ElasticNet()}

for i in models:
  models[i].fit(X_train,y_train)
  accuracy = models[i].score(X_test,y_test)
  result[i]=[accuracy]
pd.DataFrame(result)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.532e+11, tolerance: 6.151e+08
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.057e+11, tolerance: 6.151e+08
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive


LinearRegression     Lasso     Ridge  ElasticNet
0          0.865176  0.865181  0.865122    0.852204

# Train a regression model using PCA with 2 compnents

In [110]:
reg=LassoCV()

In [111]:
reg.fit(p_components,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1571: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV()

In [112]:
reg.coef_

array([0.25246753, 0.02131295])

In [116]:
reg.intercept_

1.8239930215884723e-16